name: CI/CD
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  security_tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run a script
      id: step1
      run: echo "hello world"

    - name: If step succeeds
      if: success() && steps.step1.outcome == 'success'
      run: echo "Step succeeded - send a slack message to the channel, create a new release"

    - name: If step fails
      if: failure() && steps.step1.outcome == 'failure'
      run: echo "Step failed - send a slack message to the channel, create an issue"

  fail:
    needs: security_tests
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Post fail to slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C077JHC7A6M"
          slack-message: "Your action failed :/"
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      - name: Create an issue
        env:
            GH_TOKEN: ${{secrets.PAT}}
        run: gh issue create --title "Security test failed" --body "The security test failed, please check the logs"

  pass:
    needs: security_tests
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Post success to slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C077JHC7A6M"
          slack-message: "Your action passed :D"
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
      - name: 'Checkout repository'
        uses: actions/checkout@v4
      
      
      - name: Save tag name to file
        run: gh release list --json tagName -q '.[].tagName' > tag_name.txt
        env:
            GH_TOKEN: ${{secrets.PAT}}
      - name: Add one to minor version
        run: |
            tag_name=$(cat tag_name.txt)
            IFS='.' read -r major minor patch <<< "$tag_name"
            echo "$major.$minor.$((patch+1))" > new_tag.txt
            echo "New tag: $(cat new_tag.txt)"
        shell: bash
      - name: Create a new release
        run: |
            new_tag=$(cat new_tag.txt)
            gh release create $new_tag
        env:
            GH_TOKEN: ${{secrets.PAT}}