name: Send Slack Message

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  notify-push:
    runs-on: ubuntu-latest
    steps:
      - name: Post to slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.26.0
        with:
          channel-id: "C077JHC7A6M"
          slack-message: "Hey man I love fish food and also the main branch of your repository Week-2-Demo just got pushed to"
        env:
          SLACK_BOT_TOKEN: ${{secrets.SLACK_BOT_TOKEN}}
          
